spring.application.name=demosec
spring.datasource.url=jdbc:postgresql://ep-weathered-river-b5i89mpc.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
# spring.datasource.url=jdbc:postgresql://neondb_owner:npg_DKm2Fqvcyg4H@ep-weathered-river-b5i89mpc.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DKm2Fqvcyg4H
#Numero maximo de conexiones en el pool
spring.datasource.hikari.maximum-pool-size=1
# Tiempo máximo para obtener una conexión del pool 
spring.datasource.hikari.connection-timeout=30000